# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8a3541ff43b8795d4b3f3dda39a70c7ce35eb40d6f0edbc3cf952ebcd2e42473e9336a10f325ea9b9d630fc5791ac7f98084d9e3ce7cf22e93af219c4d36f57

test:
  secret_key_base: 6cb2d2ed9d579c63ae5cac52793aa430db1c4c60d838fa15874e5683583477b72d18b05319b6faa681c2bf0710eca07fbe86bf9be087e6dabb48a837561515f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
